INSERT INTO PRODUCT(NAME,DESCRIPTION) VALUES('Iphone 0','Iphone 0 details');
INSERT INTO PRODUCT(NAME,DESCRIPTION) VALUES('Iphone 1','Iphone 1 details');
INSERT INTO PRODUCT(NAME,DESCRIPTION) VALUES('Iphone 2','Iphone 2 details');